services:
  - type: web
    name: socketio-chat-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://your-frontend-vercel-url.vercel.app
      - key: PORT
        value: 10000
